/* ข้อมูลจริงของการแข่งขัน — ใช้แสดงผลเมื่อยังไม่ได้ตั้งค่า Supabase
   ไฟล์นี้สร้างจาก Google Sheet ใบสมัครและผังสาย Challonge
   ข้อมูลชุดเดียวกันถูก seed ลงฐานข้อมูลใน supabase/migrations/0002_real_data.sql */
import type {
  Faq,
  GalleryItem,
  Game,
  Match,
  NewsPost,
  Prize,
  Rule,
  ScheduleItem,
  Settings,
  Sponsor,
  Team,
} from "./types";

export const CHALLONGE_URLS = {
  junior: "https://challonge.com/brtyw1pu",
  senior: "https://challonge.com/qny8pazw",
} as const;

export const fallbackSettings: Settings = {
  event_name: "การแข่งขันกีฬาอีสปอร์ต ROV TOURNAMENT 2026",
  event_short: "OBEC × BENCHAN ESPORTS",
  tagline:
    "การแข่งขันกีฬานักเรียน นักศึกษาและประชาชน ชิงชนะเลิศแห่งจังหวัดจันทบุรี ประจำปี 2569",
  start_at: "2026-09-09T08:30:00+07:00",
  end_at: "2026-09-10T17:00:00+07:00",
  venue_name: "หอประชุมชินวรประทานวิทยาสิทธิ์ โรงเรียนเบญจมราชูทิศ จังหวัดจันทบุรี",
  venue_address: "ถนนศรียานุสรณ์ ตำบลวัดใหม่ อำเภอเมืองจันทบุรี จังหวัดจันทบุรี 22000",
  venue_maps_url:
    "https://www.google.com/maps/search/?api=1&query=%E0%B9%82%E0%B8%A3%E0%B8%87%E0%B9%80%E0%B8%A3%E0%B8%B5%E0%B8%A2%E0%B8%99%E0%B9%80%E0%B8%9A%E0%B8%8D%E0%B8%88%E0%B8%A1%E0%B8%A3%E0%B8%B2%E0%B8%8A%E0%B8%B9%E0%B8%97%E0%B8%B4%E0%B8%A8+%E0%B8%88%E0%B8%B1%E0%B8%99%E0%B8%97%E0%B8%9A%E0%B8%B8%E0%B8%A3%E0%B8%B5",
  register_open: false,
  register_deadline: "2026-08-20T23:59:00+07:00",
  live_note: "ผลการแข่งขันอัปเดตสดจากโต๊ะกรรมการหน้างาน",
  contact_line: "@benchan-esports",
  contact_phone: "039-311-170",
  contact_facebook: "https://www.facebook.com/",
};

export const fallbackGames: Game[] = [
  {
    id: "g1",
    slug: "rov",
    name: "RoV",
    subtitle: "Arena of Valor",
    format: "แพ้คัดออก (Knockout) ทุกรอบ · Bo3 ทุกแมตช์",
    players_per_team: "5 + 1",
    numeral: "๑",
    sort: 1,
  },
];

export const fallbackTeams: Team[] = [
  {
    id: "t01",
    slug: "shadowreaper",
    name: "ShadowReaper(เงายมทูตปีศาจ)",
    school: "โรงเรียนเบญจมราชูทิศ จังหวัดจันทบุรี",
    district: null,
    division: "junior",
    teacher: "ณัชชา สิงห์จวง",
    seed: 1,
    logo_url: null,
    color: "#22429E",
    note: null,
    status: "approved",
    players: [
    { id: "t01p1", team_id: "t01", name: "เด็กชายพีรพัฒน์ อิ่มรัตน์", ign: null, level: "ม.1/4", role: null, is_sub: false, sort: 1 },
    { id: "t01p2", team_id: "t01", name: "เด็กชายปัณณวิชญ มโนรมย์ภัทรสาร", ign: null, level: "ม.1/4", role: null, is_sub: false, sort: 2 },
    { id: "t01p3", team_id: "t01", name: "เด็กชายก้องกฤษดา สังฆธรรม", ign: null, level: "ม.1/4", role: null, is_sub: false, sort: 3 },
    { id: "t01p4", team_id: "t01", name: "เด็กชายธีร์วริทธิ์ คงเมือง", ign: null, level: "ม.1/4", role: null, is_sub: false, sort: 4 },
    { id: "t01p5", team_id: "t01", name: "เด็กชายณัฐวุฒิ อิ่มสมบูรณ์", ign: null, level: "ม.1/4", role: null, is_sub: false, sort: 5 },
    { id: "t01p6", team_id: "t01", name: "เด็กชายภคิน บัลลังการ", ign: null, level: "ม.1/4", role: null, is_sub: true, sort: 6 },
    ],
  },
  {
    id: "t02",
    slug: "junior-02",
    name: "ดนัยไก่กรอบ",
    school: "โรงเรียนเบญจมราชูทิศ จังหวัดจันทบุรี",
    district: null,
    division: "junior",
    teacher: "นายณัฐสิชณ์ โพธิ์ศรี",
    seed: 2,
    logo_url: null,
    color: "#C0322A",
    note: null,
    status: "approved",
    players: [
    { id: "t02p1", team_id: "t02", name: "เด็กชายกันฐย์ธีร์ ธัญญโชติ", ign: null, level: "ม.1/10", role: null, is_sub: false, sort: 1 },
    { id: "t02p2", team_id: "t02", name: "เด็กชายชยพล สมบัติเจริญ", ign: null, level: "ม.1/10", role: null, is_sub: false, sort: 2 },
    { id: "t02p3", team_id: "t02", name: "เด็กชายฐานพัฒน์ แกะมา", ign: null, level: "ม.1/10", role: null, is_sub: false, sort: 3 },
    { id: "t02p4", team_id: "t02", name: "เด็กชายณัฐดนัย ลำใยหวาน", ign: null, level: "ม.1/10", role: null, is_sub: false, sort: 4 },
    { id: "t02p5", team_id: "t02", name: "เด็กชายก้องภพ รักญาติ", ign: null, level: "ม.1/10", role: null, is_sub: false, sort: 5 },
    { id: "t02p6", team_id: "t02", name: "เด็กชายพรพิพัฒน์ หอมเกษร", ign: null, level: "ม.1/10", role: null, is_sub: true, sort: 6 },
    ],
  },
  {
    id: "t03",
    slug: "junior-03",
    name: "ป๋าอ้นสั่งลุย",
    school: "โรงเรียนเบญจมราชูทิศ จังหวัดจันทบุรี",
    district: null,
    division: "junior",
    teacher: "นายเอกพล พันธ์คำ",
    seed: 3,
    logo_url: null,
    color: "#1E7A52",
    note: null,
    status: "approved",
    players: [
    { id: "t03p1", team_id: "t03", name: "เด็กชายอัครพล บุบผามาลัย", ign: null, level: "ม.2/9", role: null, is_sub: false, sort: 1 },
    { id: "t03p2", team_id: "t03", name: "เด็กชายณัฐชนนท์ ศิริพรมนัส", ign: null, level: "ม.2/9", role: null, is_sub: false, sort: 2 },
    { id: "t03p3", team_id: "t03", name: "เด็กชายเสฏฐวุฒิ คำเพ็ชร์", ign: null, level: "ม.2/9", role: null, is_sub: false, sort: 3 },
    { id: "t03p4", team_id: "t03", name: "เด็กชายศิวัช ทับทิมทอง", ign: null, level: "ม.2/10", role: null, is_sub: false, sort: 4 },
    { id: "t03p5", team_id: "t03", name: "เด็กชายนัธทวัฒน์ คำอ่อน", ign: null, level: "ม.2/9", role: null, is_sub: false, sort: 5 },
    { id: "t03p6", team_id: "t03", name: "เด็กชายปัณธวัฒน์ เปี่ยมบัณฑิต", ign: null, level: "ม.2/9", role: null, is_sub: true, sort: 6 },
    ],
  },
  {
    id: "t04",
    slug: "junior-04",
    name: "เส้นเซวิก",
    school: "โรงเรียนเบญจมราชูทิศ จังหวัดจันทบุรี",
    district: null,
    division: "junior",
    teacher: "นางสาวกนกอร แสงทอง",
    seed: 4,
    logo_url: null,
    color: "#0D5C73",
    note: null,
    status: "approved",
    players: [
    { id: "t04p1", team_id: "t04", name: "เด็กชายชนาธิป พิมธิค้อ", ign: null, level: "ม.3/9", role: null, is_sub: false, sort: 1 },
    { id: "t04p2", team_id: "t04", name: "นาย ภูปกรณ์ เพิ่มผล", ign: null, level: "ม.3/9", role: null, is_sub: false, sort: 2 },
    { id: "t04p3", team_id: "t04", name: "เด็กชายชินวัตร เฉลิมมิตร", ign: null, level: "ม.3/9", role: null, is_sub: false, sort: 3 },
    { id: "t04p4", team_id: "t04", name: "เด็ดชายภูปกรณ์ มั่นพลศรี", ign: null, level: "ม.3/9", role: null, is_sub: false, sort: 4 },
    { id: "t04p5", team_id: "t04", name: "เด็กชายธนกฤต แสวงธรรม", ign: null, level: "ม.3/9", role: null, is_sub: false, sort: 5 },
    { id: "t04p6", team_id: "t04", name: "เด็กชายอัฐภิญญา เทพประสิทธิ์", ign: null, level: "ม.3/9", role: null, is_sub: true, sort: 6 },
    ],
  },
  {
    id: "t05",
    slug: "junior-05",
    name: "ผมรักแม่เดลครับผมรักแม่วรรณครับ",
    school: "โรงเรียนเบญจมราชูทิศ จังหวัดจันทบุรี",
    district: null,
    division: "junior",
    teacher: "นายธันยพงศ์ วัฒนศักดิ์",
    seed: 5,
    logo_url: null,
    color: "#6B3FA0",
    note: null,
    status: "approved",
    players: [
    { id: "t05p1", team_id: "t05", name: "เด็กชายวัสสพล ใจห้าว", ign: null, level: "ม.3/8", role: null, is_sub: false, sort: 1 },
    { id: "t05p2", team_id: "t05", name: "เด็กชายอนุศิษฏ์ สงเคราะห์", ign: null, level: "ม.3/8", role: null, is_sub: false, sort: 2 },
    { id: "t05p3", team_id: "t05", name: "เด็กชายวราโชติ เจริญถ่องแท้", ign: null, level: "ม.3/8", role: null, is_sub: false, sort: 3 },
    { id: "t05p4", team_id: "t05", name: "เด็กชายภูริภัสร์ ช้างนวล", ign: null, level: "ม.3/8", role: null, is_sub: false, sort: 4 },
    { id: "t05p5", team_id: "t05", name: "เด็กชายราเชน จันทเหี้ยม", ign: null, level: "ม.3/8", role: null, is_sub: false, sort: 5 },
    { id: "t05p6", team_id: "t05", name: "เด็กชายสิรวิชญ์ ประมวล", ign: null, level: "ม.3/8", role: null, is_sub: true, sort: 6 },
    ],
  },
  {
    id: "t06",
    slug: "junior-06",
    name: "× คู่ที่23ที่หายไป🙂‍↕️",
    school: "โรงเรียนเบญจมราชูทิศ จังหวัดจันทบุรี",
    district: null,
    division: "junior",
    teacher: "นางสาว อังคณา ฟูคณะ",
    seed: 6,
    logo_url: null,
    color: "#B4841B",
    note: null,
    status: "approved",
    players: [
    { id: "t06p1", team_id: "t06", name: "เด็กชายภูวณัฏฐ์ คลังสุวรรณ", ign: null, level: "ม.3/6", role: null, is_sub: false, sort: 1 },
    { id: "t06p2", team_id: "t06", name: "เด็กชายชยพัทธ์ พยัคฆ์วิเชียร", ign: null, level: "ม.3/6", role: null, is_sub: false, sort: 2 },
    { id: "t06p3", team_id: "t06", name: "เด็กชายจิโรภาส นามวงศ์", ign: null, level: "ม.3/6", role: null, is_sub: false, sort: 3 },
    { id: "t06p4", team_id: "t06", name: "นายชลธรรม วัชชะกิตติกรณ์", ign: null, level: "ม.3/6", role: null, is_sub: false, sort: 4 },
    { id: "t06p5", team_id: "t06", name: "นายจิรายุ ฝักเครือ", ign: null, level: "ม.3/6", role: null, is_sub: false, sort: 5 },
    { id: "t06p6", team_id: "t06", name: "เด็กชายเสรฐวุฒิ วรรณสิน", ign: null, level: "ม.3/6", role: null, is_sub: true, sort: 6 },
    ],
  },
  {
    id: "t07",
    slug: "vex",
    name: "VEX",
    school: "โรงเรียนเบญจมราชูทิศ จังหวัดจันทบุรี",
    district: null,
    division: "junior",
    teacher: "พงษ์ทวิช วนพงษ์",
    seed: 7,
    logo_url: null,
    color: "#3B4A63",
    note: null,
    status: "approved",
    players: [
    { id: "t07p1", team_id: "t07", name: "เด็กชายกรวิชญ์ เครือวัลย์", ign: null, level: "ม.1/6", role: null, is_sub: false, sort: 1 },
    { id: "t07p2", team_id: "t07", name: "เด็กชายพลลภัตม์ ทรัพย์จันทร์", ign: null, level: "ม.1/6", role: null, is_sub: false, sort: 2 },
    { id: "t07p3", team_id: "t07", name: "เด็กชายธนเศรษฐ์ เนตรสมานนท์", ign: null, level: "ม.1/6", role: null, is_sub: false, sort: 3 },
    { id: "t07p4", team_id: "t07", name: "เด็กชายอติคุณ ชนะสิทธิ์", ign: null, level: "ม.1/6", role: null, is_sub: false, sort: 4 },
    { id: "t07p5", team_id: "t07", name: "เด็กชายพลช เกิดเสม", ign: null, level: "ม.1/6", role: null, is_sub: false, sort: 5 },
    { id: "t07p6", team_id: "t07", name: "เด็กชายชิณท์ณภัทร อิทธิอนุวัตร์", ign: null, level: "ม.1/6", role: null, is_sub: true, sort: 6 },
    ],
  },
  {
    id: "t08",
    slug: "junior-08",
    name: "นักล่าป้อมในตำนาน",
    school: "โรงเรียนเบญจมราชูทิศ จังหวัดจันทบุรี",
    district: null,
    division: "junior",
    teacher: "นางสาววษมล ศรีวิรัญ",
    seed: 8,
    logo_url: null,
    color: "#8A3B12",
    note: null,
    status: "approved",
    players: [
    { id: "t08p1", team_id: "t08", name: "เด็กชายชุติชัย ยิ้มพาย", ign: null, level: "ม.2/8", role: null, is_sub: false, sort: 1 },
    { id: "t08p2", team_id: "t08", name: "เด็กชายบรรยวัสถ์ แสงคำมี", ign: null, level: "ม.2/8", role: null, is_sub: false, sort: 2 },
    { id: "t08p3", team_id: "t08", name: "เด็กชายวีพงศ์ มหามาตย์", ign: null, level: "ม.2/3", role: null, is_sub: false, sort: 3 },
    { id: "t08p4", team_id: "t08", name: "เด็กชายพีรวิชญ์ พิมพา", ign: null, level: "ม.2/8", role: null, is_sub: false, sort: 4 },
    { id: "t08p5", team_id: "t08", name: "เด็กชายประกาคิด วารีเสาวคนธ์", ign: null, level: "ม.2/8", role: null, is_sub: false, sort: 5 },
    { id: "t08p6", team_id: "t08", name: "เด็กชายอัมรินทร์ ช่วยชาติ", ign: null, level: "ม.2/7", role: null, is_sub: true, sort: 6 },
    ],
  },
  {
    id: "t09",
    slug: "limitless",
    name: "Limitless (ลิมิตเลส)",
    school: "โรงเรียนเบญจมราชูทิศ จังหวัดจันทบุรี",
    district: null,
    division: "junior",
    teacher: "นายณัฐสิชณ์ โพธิ์ศรี",
    seed: 9,
    logo_url: null,
    color: "#146C63",
    note: null,
    status: "approved",
    players: [
    { id: "t09p1", team_id: "t09", name: "เด็กชายอติวัณณ์ เตียวประเสริฐ", ign: null, level: "ม.1/10", role: null, is_sub: false, sort: 1 },
    { id: "t09p2", team_id: "t09", name: "เด็กชายธรรมนูญ สุขผลานันท์", ign: null, level: "ม.1/10", role: null, is_sub: false, sort: 2 },
    { id: "t09p3", team_id: "t09", name: "เด็กชายชยากร นวลมะ", ign: null, level: "ม.1/10", role: null, is_sub: false, sort: 3 },
    { id: "t09p4", team_id: "t09", name: "เด็กชายสมพงษ์ จัทนร์ไพศาลสิน", ign: null, level: "ม.1/10", role: null, is_sub: false, sort: 4 },
    { id: "t09p5", team_id: "t09", name: "เด็กชายเอกภูศิษฐ์ อมรศักดิ์ฐากุล", ign: null, level: "ม.1/10", role: null, is_sub: false, sort: 5 },
    { id: "t09p6", team_id: "t09", name: "เด็กชายปกรณ์ธรรม ทองธรรม", ign: null, level: "ม.1/10", role: null, is_sub: true, sort: 6 },
    ],
  },
  {
    id: "t10",
    slug: "domino",
    name: "DOMINO",
    school: "โรงเรียนเบญจมราชูทิศ จังหวัดจันทบุรี",
    district: null,
    division: "junior",
    teacher: "นางสาวกุลธิดา เซียงหนู",
    seed: 10,
    logo_url: null,
    color: "#7A2E4A",
    note: null,
    status: "approved",
    players: [
    { id: "t10p1", team_id: "t10", name: "เด็กชายศิวนาถ แกลัวกล้า", ign: null, level: "ม.1/7", role: null, is_sub: false, sort: 1 },
    { id: "t10p2", team_id: "t10", name: "เด็กชายพิธาน พยุงกิจ", ign: null, level: "ม.1/7", role: null, is_sub: false, sort: 2 },
    { id: "t10p3", team_id: "t10", name: "เด็กชายณัฐภูมินทร์ แก้วบัวดี", ign: null, level: "ม.1/7", role: null, is_sub: false, sort: 3 },
    { id: "t10p4", team_id: "t10", name: "เด็กชายวุฒิวัฒน์ แก้วเกษ", ign: null, level: "ม.1/7", role: null, is_sub: false, sort: 4 },
    { id: "t10p5", team_id: "t10", name: "เด็กชายอนันต์ชลธี แก่กำเหนิด", ign: null, level: "ม.1/7", role: null, is_sub: false, sort: 5 },
    { id: "t10p6", team_id: "t10", name: "เด็กชายไชยวัฒน์ ยิ้มศรี", ign: null, level: "ม.1/7", role: null, is_sub: true, sort: 6 },
    ],
  },
  {
    id: "t11",
    slug: "barenza-brz",
    name: "Barenza (BRZ)",
    school: "โรงเรียนเบญจมราชูทิศ จังหวัดจันทบุรี",
    district: null,
    division: "junior",
    teacher: "นางสาวเอมมิกา กลิ่นขจร",
    seed: 11,
    logo_url: null,
    color: "#2F5D2F",
    note: null,
    status: "approved",
    players: [
    { id: "t11p1", team_id: "t11", name: "เด็กหญิงณัฐณิชา พานิชกุล", ign: null, level: "ม.1/3", role: null, is_sub: false, sort: 1 },
    { id: "t11p2", team_id: "t11", name: "เด็กชายนิพพิชฌน์โชติ สุขเหลือ", ign: null, level: "ม.1/8", role: null, is_sub: false, sort: 2 },
    { id: "t11p3", team_id: "t11", name: "เด็กชายพีรัชชัย ผ่องสวัสดิ์", ign: null, level: "ม.1/5", role: null, is_sub: false, sort: 3 },
    { id: "t11p4", team_id: "t11", name: "เด็กชายภูริณัฐ เทพบรรชา", ign: null, level: "ม.1/1", role: null, is_sub: false, sort: 4 },
    { id: "t11p5", team_id: "t11", name: "เด็กชายธีร์ดนัย รุ่งศิริยืนยง", ign: null, level: "ม.1/3", role: null, is_sub: false, sort: 5 },
    { id: "t11p6", team_id: "t11", name: "เด็กชายปภังกร อังคะหิรัญ", ign: null, level: "ม.1/8", role: null, is_sub: true, sort: 6 },
    ],
  },
  {
    id: "t12",
    slug: "rovbjm",
    name: "RovBJM",
    school: "โรงเรียนเบญจมราชูทิศ จังหวัดจันทบุรี",
    district: null,
    division: "junior",
    teacher: "นายวรยุธ ท่าหลวง",
    seed: 12,
    logo_url: null,
    color: "#54327A",
    note: null,
    status: "approved",
    players: [
    { id: "t12p1", team_id: "t12", name: "เด็กชายกฤติเดช เมืองพินท", ign: null, level: "ม.1/7", role: null, is_sub: false, sort: 1 },
    { id: "t12p2", team_id: "t12", name: "เด็กชายณัฐภูมิ แก้วเอี่ยม", ign: null, level: "ม.1/7", role: null, is_sub: false, sort: 2 },
    { id: "t12p3", team_id: "t12", name: "เด็กชายปัณณธร แซ่โค้ว", ign: null, level: "ม.1/7", role: null, is_sub: false, sort: 3 },
    { id: "t12p4", team_id: "t12", name: "เด็กชายกันต์กวี ดาราพงษ์", ign: null, level: "ม.1/3", role: null, is_sub: false, sort: 4 },
    { id: "t12p5", team_id: "t12", name: "เด็กชายวีรวัตร คุ้มแก้ว", ign: null, level: "ม.1/3", role: null, is_sub: false, sort: 5 },
    { id: "t12p6", team_id: "t12", name: "เด็กชายณัฐวรรชน์ บุญมา", ign: null, level: "ม.1/7", role: null, is_sub: true, sort: 6 },
    ],
  },
  {
    id: "t13",
    slug: "junior-13",
    name: "จั๊กกะด่งด๊งโดย",
    school: "โรงเรียนเบญจมราชูทิศ จังหวัดจันทบุรี",
    district: null,
    division: "junior",
    teacher: "นางสาวสุวิมล ถนอมจิต",
    seed: 13,
    logo_url: null,
    color: "#9A5B10",
    note: null,
    status: "approved",
    players: [
    { id: "t13p1", team_id: "t13", name: "เด็กหญิงพัชรพรรณ ศรีสถาน", ign: null, level: "ม.1/1", role: null, is_sub: false, sort: 1 },
    { id: "t13p2", team_id: "t13", name: "เด็กชายจิตติพัฒน์ อยู่พิทักษ์", ign: null, level: "ม.1/1", role: null, is_sub: false, sort: 2 },
    { id: "t13p3", team_id: "t13", name: "เด็กชายชิติพัทธ์ เดชพิมล", ign: null, level: "ม.1/1", role: null, is_sub: false, sort: 3 },
    { id: "t13p4", team_id: "t13", name: "เด็กหญิงอคัมย์สิริ เกยูรวรรณ์", ign: null, level: "ม.1/1", role: null, is_sub: false, sort: 4 },
    { id: "t13p5", team_id: "t13", name: "เด็กชายภธรเดช เทียนอยู่", ign: null, level: "ม.1/6", role: null, is_sub: false, sort: 5 },
    { id: "t13p6", team_id: "t13", name: "เด็กหญิงศิวกานต์ ขจรกลิ่น", ign: null, level: "ม.1/1", role: null, is_sub: true, sort: 6 },
    ],
  },
  {
    id: "t14",
    slug: "one-thousand-minus-seven",
    name: "One thousand minus seven",
    school: "โรงเรียนเบญจมราชูทิศ จังหวัดจันทบุรี",
    district: null,
    division: "junior",
    teacher: "นายดิศร คำฮัง",
    seed: 14,
    logo_url: null,
    color: "#1F4E79",
    note: null,
    status: "approved",
    players: [
    { id: "t14p1", team_id: "t14", name: "นายวิชญพงศ์ เกษไชย", ign: null, level: "ม.3/7", role: null, is_sub: false, sort: 1 },
    { id: "t14p2", team_id: "t14", name: "เด็กชายกันต์ อ่อนละม่อม", ign: null, level: "ม.3/7", role: null, is_sub: false, sort: 2 },
    { id: "t14p3", team_id: "t14", name: "นายปัณณวัฒน์ จอศักดิ์", ign: null, level: "ม.3/7", role: null, is_sub: false, sort: 3 },
    { id: "t14p4", team_id: "t14", name: "เด็กชายพรรษไนย กงไกรลาส", ign: null, level: "ม.3/7", role: null, is_sub: false, sort: 4 },
    { id: "t14p5", team_id: "t14", name: "นางสาวพัทธิชา โชติธรรมจักดิ์", ign: null, level: "ม.3/5", role: null, is_sub: false, sort: 5 },
    ],
  },
  {
    id: "t15",
    slug: "junior-15",
    name: "ทับ4หมี่เกี้ยว",
    school: "โรงเรียนเบญจมราชูทิศ จังหวัดจันทบุรี",
    district: null,
    division: "junior",
    teacher: "นายภานุพงษ์ รัตนาลัย",
    seed: 15,
    logo_url: null,
    color: "#7C1F2E",
    note: null,
    status: "approved",
    players: [
    { id: "t15p1", team_id: "t15", name: "เด็กชายอัยยศักดิ์ รื่นรมย์", ign: null, level: "ม.3/4", role: null, is_sub: false, sort: 1 },
    { id: "t15p2", team_id: "t15", name: "เด็กชายนิติยศ แก้วงาม", ign: null, level: "ม.3/4", role: null, is_sub: false, sort: 2 },
    { id: "t15p3", team_id: "t15", name: "เด็กชายกิตติ สัญญะรัตน์", ign: null, level: "ม.3/4", role: null, is_sub: false, sort: 3 },
    { id: "t15p4", team_id: "t15", name: "เด็กชายกันต์ระพี เยี่ยมรักชาติ", ign: null, level: "ม.3/4", role: null, is_sub: false, sort: 4 },
    { id: "t15p5", team_id: "t15", name: "เด็กชายภูมิพัชร์ ศรีสัสดิ์", ign: null, level: "ม.3/4", role: null, is_sub: false, sort: 5 },
    { id: "t15p6", team_id: "t15", name: "เด็กชายเจษฎาพิชญ์ พิสิษฐ์นิษฐ์", ign: null, level: "ม.3/4", role: null, is_sub: true, sort: 6 },
    ],
  },
  {
    id: "t16",
    slug: "phoenix",
    name: "Phoenix",
    school: "โรงเรียนเบญจมราชูทิศ จังหวัดจันทบุรี",
    district: null,
    division: "junior",
    teacher: "Mr.Kirill Belov",
    seed: 16,
    logo_url: null,
    color: "#356859",
    note: null,
    status: "approved",
    players: [
    { id: "t16p1", team_id: "t16", name: "เด็กชายกฤศณกร สิรวิทูร", ign: null, level: "ม.2/3", role: null, is_sub: false, sort: 1 },
    { id: "t16p2", team_id: "t16", name: "เด็กชายภพธร สุริยะจันทร์", ign: null, level: "ม.2/5", role: null, is_sub: false, sort: 2 },
    { id: "t16p3", team_id: "t16", name: "เด็กชายภคพงษ์ พูลพฤกษ์", ign: null, level: "ม.2/5", role: null, is_sub: false, sort: 3 },
    { id: "t16p4", team_id: "t16", name: "เด็กชายเพชร รําพึงกูล", ign: null, level: "ม.2/5", role: null, is_sub: false, sort: 4 },
    { id: "t16p5", team_id: "t16", name: "เด็กชายรัชพล มาอินทร์", ign: null, level: "ม.2/3", role: null, is_sub: false, sort: 5 },
    { id: "t16p6", team_id: "t16", name: "เด็กชายณัชพล นาวารัตน์", ign: null, level: "ม.2/5", role: null, is_sub: true, sort: 6 },
    ],
  },
  {
    id: "t17",
    slug: "benchan-esports-2",
    name: "BENCHAN Esports 2",
    school: "โรงเรียนเบญจมราชูทิศ จังหวัดจันทบุรี",
    district: null,
    division: "senior",
    teacher: "นางสาวชญาณัฏฐ์ คำรอด",
    seed: 1,
    logo_url: null,
    color: "#22429E",
    note: null,
    status: "approved",
    players: [
    { id: "t17p1", team_id: "t17", name: "นายอชิตะ ชนะไพรี", ign: null, level: "ม.6/4", role: null, is_sub: false, sort: 1 },
    { id: "t17p2", team_id: "t17", name: "นายสุรธัช บรรเทาวงษ์", ign: null, level: "ม.6/4", role: null, is_sub: false, sort: 2 },
    { id: "t17p3", team_id: "t17", name: "นายอชิระ สนั่นวงค์", ign: null, level: "ม.6/4", role: null, is_sub: false, sort: 3 },
    { id: "t17p4", team_id: "t17", name: "นายศุภวิชญ์ ภานุเพ็ญ", ign: null, level: "ม.6/9", role: null, is_sub: false, sort: 4 },
    { id: "t17p5", team_id: "t17", name: "นายปัณณวัฒน์ รัตตะรมย์", ign: null, level: "ม.6/4", role: null, is_sub: false, sort: 5 },
    { id: "t17p6", team_id: "t17", name: "นายนิรัชชุณห์ อรัมสัจจากูล", ign: null, level: "ม.6/4", role: null, is_sub: true, sort: 6 },
    ],
  },
  {
    id: "t18",
    slug: "benchan-esports",
    name: "BENCHAN Esports",
    school: "โรงเรียนเบญจมราชูทิศ จังหวัดจันทบุรี",
    district: null,
    division: "senior",
    teacher: "นางสาวชญาณัฏฐ์ คำรอด",
    seed: 2,
    logo_url: null,
    color: "#C0322A",
    note: null,
    status: "approved",
    players: [
    { id: "t18p1", team_id: "t18", name: "นายปวินทร์ คงขวัญ", ign: null, level: "ม.5/5", role: null, is_sub: false, sort: 1 },
    { id: "t18p2", team_id: "t18", name: "นายแทนคุณ บุตรจันทร์", ign: null, level: "ม.5/5", role: null, is_sub: false, sort: 2 },
    { id: "t18p3", team_id: "t18", name: "นายนิบุณ เจริญยศ", ign: null, level: "ม.5/5", role: null, is_sub: false, sort: 3 },
    { id: "t18p4", team_id: "t18", name: "นายภาม พานิชผล", ign: null, level: "ม.5/5", role: null, is_sub: false, sort: 4 },
    { id: "t18p5", team_id: "t18", name: "นายฐิติพงษ์ คำภาพันธ์", ign: null, level: "ม.5/5", role: null, is_sub: false, sort: 5 },
    ],
  },
  {
    id: "t19",
    slug: "bjallstar",
    name: "BJallstar",
    school: "โรงเรียนเบญจมราชูทิศ จังหวัดจันทบุรี",
    district: null,
    division: "senior",
    teacher: "นางอรพินท์  แนช",
    seed: 3,
    logo_url: null,
    color: "#1E7A52",
    note: null,
    status: "approved",
    players: [
    { id: "t19p1", team_id: "t19", name: "นายภาดล สุคนธประทีป", ign: null, level: "ม.5/16", role: null, is_sub: false, sort: 1 },
    { id: "t19p2", team_id: "t19", name: "นายศุภวิชญ์  พิลาวุธ", ign: null, level: "ม.5/12", role: null, is_sub: false, sort: 2 },
    { id: "t19p3", team_id: "t19", name: "นายมนวรรธน์  รุจีจิต", ign: null, level: "ม.5/16", role: null, is_sub: false, sort: 3 },
    { id: "t19p4", team_id: "t19", name: "นายชยธร พึ่งฝั่ง", ign: null, level: "ม.5/4", role: null, is_sub: false, sort: 4 },
    { id: "t19p5", team_id: "t19", name: "นายไรอันจอห์น  สแปรี่", ign: null, level: "ม.5/11", role: null, is_sub: false, sort: 5 },
    { id: "t19p6", team_id: "t19", name: "นางสาวพัชรพร  ชลประทาน", ign: null, level: "ม.5/16", role: null, is_sub: true, sort: 6 },
    ],
  },
  {
    id: "t20",
    slug: "valkyrie",
    name: "Valkyrie",
    school: "โรงเรียนเบญจมราชูทิศ จังหวัดจันทบุรี",
    district: null,
    division: "senior",
    teacher: "นายสิรภพ คุ้มพ่วงดี",
    seed: 4,
    logo_url: null,
    color: "#0D5C73",
    note: null,
    status: "approved",
    players: [
    { id: "t20p1", team_id: "t20", name: "นางสาวณอร จันดอน", ign: null, level: "ม.5/8", role: null, is_sub: false, sort: 1 },
    { id: "t20p2", team_id: "t20", name: "นางสาวกรัณฑรัตน์ ศิริรัตน์", ign: null, level: "ม.5/8", role: null, is_sub: false, sort: 2 },
    { id: "t20p3", team_id: "t20", name: "นางสาวสุคนธ์วดี ซอน", ign: null, level: "ม.5/8", role: null, is_sub: false, sort: 3 },
    { id: "t20p4", team_id: "t20", name: "นางสาวเรณุกา พานิชานุรักษ์", ign: null, level: "ม.5/4", role: null, is_sub: false, sort: 4 },
    { id: "t20p5", team_id: "t20", name: "นายทินพัน สุวรรณราช", ign: null, level: "ม.5/8", role: null, is_sub: false, sort: 5 },
    ],
  },
  {
    id: "t21",
    slug: "senior-05",
    name: "นินทาเจอรี่",
    school: "โรงเรียนเบญจมราชูทิศ จังหวัดจันทบุรี",
    district: null,
    division: "senior",
    teacher: "นางดวงกมล รักษ์สุจริต",
    seed: 5,
    logo_url: null,
    color: "#6B3FA0",
    note: null,
    status: "approved",
    players: [
    { id: "t21p1", team_id: "t21", name: "นายธันย์วริศ เหลืองอุดมชัย", ign: null, level: "ม.6/9", role: null, is_sub: false, sort: 1 },
    { id: "t21p2", team_id: "t21", name: "นายฉันทวัฒน์ พันธุ์เมือง", ign: null, level: "ม.6/9", role: null, is_sub: false, sort: 2 },
    { id: "t21p3", team_id: "t21", name: "นายธีรวัจน์ พื้นผล", ign: null, level: "ม.6/9", role: null, is_sub: false, sort: 3 },
    { id: "t21p4", team_id: "t21", name: "นายพุทธิกันต์ เเก้วคำ", ign: null, level: "ม.6/9", role: null, is_sub: false, sort: 4 },
    { id: "t21p5", team_id: "t21", name: "นายธนกฤต วรรณป้าน", ign: null, level: "ม.6/9", role: null, is_sub: false, sort: 5 },
    { id: "t21p6", team_id: "t21", name: "นายสรศักดิ์ เรืองเวชติวงษ์", ign: null, level: "ม.6/9", role: null, is_sub: true, sort: 6 },
    ],
  },
  {
    id: "t22",
    slug: "senior-06",
    name: "มาเตโอ",
    school: "โรงเรียนเบญจมราชูทิศ จังหวัดจันทบุรี",
    district: null,
    division: "senior",
    teacher: "นางสาวชญาณัฎฐ์ คำรอด",
    seed: 6,
    logo_url: null,
    color: "#B4841B",
    note: null,
    status: "approved",
    players: [
    { id: "t22p1", team_id: "t22", name: "นายปัญรวิชญ์ กันทา", ign: null, level: "ม.4/3", role: null, is_sub: false, sort: 1 },
    { id: "t22p2", team_id: "t22", name: "นายเมธาวิน เเสงกล้า", ign: null, level: "ม.4/11", role: null, is_sub: false, sort: 2 },
    { id: "t22p3", team_id: "t22", name: "นายพลพิสิษฐ์ ทองเเก้ว", ign: null, level: "ม.4/3", role: null, is_sub: false, sort: 3 },
    { id: "t22p4", team_id: "t22", name: "นายวายุ วารีรัตน์", ign: null, level: "ม.4/10", role: null, is_sub: false, sort: 4 },
    { id: "t22p5", team_id: "t22", name: "นายนาวา ศิริภักตร์", ign: null, level: "ม.4/8", role: null, is_sub: false, sort: 5 },
    ],
  },
  {
    id: "t23",
    slug: "senior-07",
    name: "\"เอาดงเอาดี\"",
    school: "โรงเรียนเบญจมราชูทิศ จังหวัดจันทบุรี",
    district: null,
    division: "senior",
    teacher: "นายนิรันต์ คายเซ่า",
    seed: 7,
    logo_url: null,
    color: "#3B4A63",
    note: null,
    status: "approved",
    players: [
    { id: "t23p1", team_id: "t23", name: "เด็กชายทีฆายุ อยู่สำราญ", ign: null, level: "ม.3/10", role: null, is_sub: false, sort: 1 },
    { id: "t23p2", team_id: "t23", name: "เด็กชายปิยวัตน์ ทางชอบ", ign: null, level: "ม.3/10", role: null, is_sub: false, sort: 2 },
    { id: "t23p3", team_id: "t23", name: "เด็กชายกวินภพ แซ่จู", ign: null, level: "ม.3/10", role: null, is_sub: false, sort: 3 },
    { id: "t23p4", team_id: "t23", name: "เด็กชายธนพัฒน์ วงเวียน", ign: null, level: "ม.3/10", role: null, is_sub: false, sort: 4 },
    { id: "t23p5", team_id: "t23", name: "เด็กชายสิรชัชพรหม จิรกิตติปกรณ์", ign: null, level: "3/10", role: null, is_sub: false, sort: 5 },
    { id: "t23p6", team_id: "t23", name: "เด็กชายนพอนันต์ เจริญรื่น", ign: null, level: "ม.3/10", role: null, is_sub: true, sort: 6 },
    ],
  },
  {
    id: "t24",
    slug: "senior-08",
    name: "บาบูนไซย่า",
    school: "โรงเรียนเบญจมราชูทิศ จังหวัดจันทบุรี",
    district: null,
    division: "senior",
    teacher: "นางดวงกมล รักษ์สุจริต",
    seed: 8,
    logo_url: null,
    color: "#8A3B12",
    note: null,
    status: "approved",
    players: [
    { id: "t24p1", team_id: "t24", name: "นายกรวิชญ์ สมประสงค์", ign: null, level: "ม.6/9", role: null, is_sub: false, sort: 1 },
    { id: "t24p2", team_id: "t24", name: "นายกฤษกร สมประสงค์", ign: null, level: "ม.6/12", role: null, is_sub: false, sort: 2 },
    { id: "t24p3", team_id: "t24", name: "นายกิตติพงศ์ เรืองศรี", ign: null, level: "ม.6/9", role: null, is_sub: false, sort: 3 },
    { id: "t24p4", team_id: "t24", name: "นายกิตติมศักดิ์ ทองดี", ign: null, level: "ม.6/12", role: null, is_sub: false, sort: 4 },
    { id: "t24p5", team_id: "t24", name: "นายภูมิพัฒน์ เข็มทอง", ign: null, level: "ม.6/9", role: null, is_sub: false, sort: 5 },
    { id: "t24p6", team_id: "t24", name: "นายตฤณ แพงพันธุ์", ign: null, level: "ม.6/9", role: null, is_sub: true, sort: 6 },
    ],
  },
  {
    id: "t25",
    slug: "fcmarwin",
    name: "FcMarwin",
    school: "โรงเรียนเบญจมราชูทิศ จังหวัดจันทบุรี",
    district: null,
    division: "senior",
    teacher: "นายทรงพล ทองมา",
    seed: 9,
    logo_url: null,
    color: "#146C63",
    note: null,
    status: "approved",
    players: [
    { id: "t25p1", team_id: "t25", name: "นายปฐพี ชาวชล", ign: null, level: "ม.6/14", role: null, is_sub: false, sort: 1 },
    { id: "t25p2", team_id: "t25", name: "นายจิรพัท มิลาน", ign: null, level: "ม.6/14", role: null, is_sub: false, sort: 2 },
    { id: "t25p3", team_id: "t25", name: "นายปุริมนาถ เชิดชูถิ่น", ign: null, level: "ม.6/14", role: null, is_sub: false, sort: 3 },
    { id: "t25p4", team_id: "t25", name: "นายวัชรพล จันทร์ที", ign: null, level: "ม.6/14", role: null, is_sub: false, sort: 4 },
    { id: "t25p5", team_id: "t25", name: "นายจักรพันธ์ คงสุข", ign: null, level: "ม.6/14", role: null, is_sub: false, sort: 5 },
    { id: "t25p6", team_id: "t25", name: "นายศุภณัฐ รัตนพันธ์", ign: null, level: "ม.6/14", role: null, is_sub: true, sort: 6 },
    ],
  },
  {
    id: "t26",
    slug: "40-60",
    name: "40/60",
    school: "โรงเรียนเบญจมราชูทิศ จังหวัดจันทบุรี",
    district: null,
    division: "senior",
    teacher: "นายธนเดช ลี้เลิศธนกุล",
    seed: 10,
    logo_url: null,
    color: "#7A2E4A",
    note: null,
    status: "approved",
    players: [
    { id: "t26p1", team_id: "t26", name: "นายนพรัตน์ เพ็ชรบดี", ign: null, level: "ม.5/11", role: null, is_sub: false, sort: 1 },
    { id: "t26p2", team_id: "t26", name: "นายกฤตกรณ์ อริยะมงคลการ", ign: null, level: "ม.5/11", role: null, is_sub: false, sort: 2 },
    { id: "t26p3", team_id: "t26", name: "นายนภัสกร ศรีพงษ์", ign: null, level: "ม.5/9", role: null, is_sub: false, sort: 3 },
    { id: "t26p4", team_id: "t26", name: "นายปุณพจน์ สุขปิติ", ign: null, level: "ม.5/11", role: null, is_sub: false, sort: 4 },
    { id: "t26p5", team_id: "t26", name: "นายณัฐดนัย มาลัยเปีย", ign: null, level: "ม.5/10", role: null, is_sub: false, sort: 5 },
    { id: "t26p6", team_id: "t26", name: "นายสรวิชญ์ สุโข", ign: null, level: "ม.5/11", role: null, is_sub: true, sort: 6 },
    ],
  },
  {
    id: "t27",
    slug: "senior-11",
    name: "ที่เด็ดIC",
    school: "โรงเรียนเบญจมราชูทิศ จังหวัดจันทบุรี",
    district: null,
    division: "senior",
    teacher: "ณัชชา สิงห์จวง",
    seed: 11,
    logo_url: null,
    color: "#2F5D2F",
    note: null,
    status: "approved",
    players: [
    { id: "t27p1", team_id: "t27", name: "เด็กชายณัฐนันท์ ภูมิผล", ign: null, level: "ม.1/4", role: null, is_sub: false, sort: 1 },
    { id: "t27p2", team_id: "t27", name: "เด็กชายฐิติวัทน์  ทิพย์สกุลเดช", ign: null, level: "ม.1/4", role: null, is_sub: false, sort: 2 },
    { id: "t27p3", team_id: "t27", name: "เด็กชายเสฎฐวุฒิ ทองกลํ่า", ign: null, level: "ม.1/4", role: null, is_sub: false, sort: 3 },
    { id: "t27p4", team_id: "t27", name: "เด็กชายติณห์ภัทร สมุยทัย", ign: null, level: "ม.1/4", role: null, is_sub: false, sort: 4 },
    { id: "t27p5", team_id: "t27", name: "เด็กชายณัฐกรณ์ ปีเจริญ", ign: null, level: "ม.1/4", role: null, is_sub: false, sort: 5 },
    { id: "t27p6", team_id: "t27", name: "เด็กชาย บุญ ไชยพงษ์", ign: null, level: "ม.1/4", role: null, is_sub: true, sort: 6 },
    ],
  },
  {
    id: "t28",
    slug: "love-mlbb",
    name: "Love Mlbb",
    school: "โรงเรียนเบญจมราชูทิศ จังหวัดจันทบุรี",
    district: null,
    division: "senior",
    teacher: "นายธีระพงษ์ สืบโสดา",
    seed: 12,
    logo_url: null,
    color: "#54327A",
    note: null,
    status: "approved",
    players: [
    { id: "t28p1", team_id: "t28", name: "นายนิติธร แสงอยู่", ign: null, level: "ม.5/5", role: null, is_sub: false, sort: 1 },
    { id: "t28p2", team_id: "t28", name: "นายอาทิตย์ น้อยถนอม", ign: null, level: "ม.5/8", role: null, is_sub: false, sort: 2 },
    { id: "t28p3", team_id: "t28", name: "นายปิยพัทย์ พวงบุบผา", ign: null, level: "ม.5/6", role: null, is_sub: false, sort: 3 },
    { id: "t28p4", team_id: "t28", name: "นายปรภัค ศรีมงคล", ign: null, level: "ม.5/13", role: null, is_sub: false, sort: 4 },
    { id: "t28p5", team_id: "t28", name: "นายพุฒินันท์ ภานุพันธ์", ign: null, level: "ม.5/4", role: null, is_sub: false, sort: 5 },
    ],
  },
  {
    id: "t29",
    slug: "quad-reaper",
    name: "Quad Reaper",
    school: "โรงเรียนเบญจมราชูทิศ จังหวัดจันทบุรี",
    district: null,
    division: "senior",
    teacher: "นายธนเดช ลี้เลิศธนกุล",
    seed: 13,
    logo_url: null,
    color: "#9A5B10",
    note: null,
    status: "approved",
    players: [
    { id: "t29p1", team_id: "t29", name: "นายจักรภัทร เพิ่มสมบูรณ์", ign: null, level: "ม.5/10", role: null, is_sub: false, sort: 1 },
    { id: "t29p2", team_id: "t29", name: "นายภควุฒิ วุฒิภัทรพงศ์", ign: null, level: "ม.4/7", role: null, is_sub: false, sort: 2 },
    { id: "t29p3", team_id: "t29", name: "นายธนเดช อยู่เจริญ", ign: null, level: "ม.5/10", role: null, is_sub: false, sort: 3 },
    { id: "t29p4", team_id: "t29", name: "นายสิริรัฐภณ คำดำ", ign: null, level: "ม.5/1", role: null, is_sub: false, sort: 4 },
    { id: "t29p5", team_id: "t29", name: "นายอติภัทร ปุริเส", ign: null, level: "ม.5/11", role: null, is_sub: false, sort: 5 },
    ],
  },
];

const teamById = Object.fromEntries(fallbackTeams.map((x) => [x.id, x]));

export const fallbackMatches: Match[] = [
  {
    id: "J-A",
    code: "J-A",
    game_slug: "rov",
    division: "junior",
    round_name: "รอบ 16 ทีมสุดท้าย",
    round_order: 1,
    slot: 1,
    team_a_id: "t01",
    team_b_id: "t16",
    label_a: null,
    label_b: null,
    score_a: null,
    score_b: null,
    best_of: 3,
    status: "wait",
    winner: null,
    scheduled_at: null,
    note: null,
    team_a: teamById["t01"],
    team_b: teamById["t16"],
  },
  {
    id: "J-B",
    code: "J-B",
    game_slug: "rov",
    division: "junior",
    round_name: "รอบ 16 ทีมสุดท้าย",
    round_order: 1,
    slot: 2,
    team_a_id: "t08",
    team_b_id: "t09",
    label_a: null,
    label_b: null,
    score_a: null,
    score_b: null,
    best_of: 3,
    status: "wait",
    winner: null,
    scheduled_at: null,
    note: null,
    team_a: teamById["t08"],
    team_b: teamById["t09"],
  },
  {
    id: "J-C",
    code: "J-C",
    game_slug: "rov",
    division: "junior",
    round_name: "รอบ 16 ทีมสุดท้าย",
    round_order: 1,
    slot: 3,
    team_a_id: "t04",
    team_b_id: "t13",
    label_a: null,
    label_b: null,
    score_a: null,
    score_b: null,
    best_of: 3,
    status: "wait",
    winner: null,
    scheduled_at: null,
    note: null,
    team_a: teamById["t04"],
    team_b: teamById["t13"],
  },
  {
    id: "J-D",
    code: "J-D",
    game_slug: "rov",
    division: "junior",
    round_name: "รอบ 16 ทีมสุดท้าย",
    round_order: 1,
    slot: 4,
    team_a_id: "t05",
    team_b_id: "t12",
    label_a: null,
    label_b: null,
    score_a: null,
    score_b: null,
    best_of: 3,
    status: "wait",
    winner: null,
    scheduled_at: null,
    note: null,
    team_a: teamById["t05"],
    team_b: teamById["t12"],
  },
  {
    id: "J-E",
    code: "J-E",
    game_slug: "rov",
    division: "junior",
    round_name: "รอบ 16 ทีมสุดท้าย",
    round_order: 1,
    slot: 5,
    team_a_id: "t02",
    team_b_id: "t15",
    label_a: null,
    label_b: null,
    score_a: null,
    score_b: null,
    best_of: 3,
    status: "wait",
    winner: null,
    scheduled_at: null,
    note: null,
    team_a: teamById["t02"],
    team_b: teamById["t15"],
  },
  {
    id: "J-F",
    code: "J-F",
    game_slug: "rov",
    division: "junior",
    round_name: "รอบ 16 ทีมสุดท้าย",
    round_order: 1,
    slot: 6,
    team_a_id: "t07",
    team_b_id: "t10",
    label_a: null,
    label_b: null,
    score_a: null,
    score_b: null,
    best_of: 3,
    status: "wait",
    winner: null,
    scheduled_at: null,
    note: null,
    team_a: teamById["t07"],
    team_b: teamById["t10"],
  },
  {
    id: "J-G",
    code: "J-G",
    game_slug: "rov",
    division: "junior",
    round_name: "รอบ 16 ทีมสุดท้าย",
    round_order: 1,
    slot: 7,
    team_a_id: "t03",
    team_b_id: "t14",
    label_a: null,
    label_b: null,
    score_a: null,
    score_b: null,
    best_of: 3,
    status: "wait",
    winner: null,
    scheduled_at: null,
    note: null,
    team_a: teamById["t03"],
    team_b: teamById["t14"],
  },
  {
    id: "J-H",
    code: "J-H",
    game_slug: "rov",
    division: "junior",
    round_name: "รอบ 16 ทีมสุดท้าย",
    round_order: 1,
    slot: 8,
    team_a_id: "t06",
    team_b_id: "t11",
    label_a: null,
    label_b: null,
    score_a: null,
    score_b: null,
    best_of: 3,
    status: "wait",
    winner: null,
    scheduled_at: null,
    note: null,
    team_a: teamById["t06"],
    team_b: teamById["t11"],
  },
  {
    id: "J-I",
    code: "J-I",
    game_slug: "rov",
    division: "junior",
    round_name: "รอบ 8 ทีมสุดท้าย",
    round_order: 2,
    slot: 1,
    team_a_id: null,
    team_b_id: null,
    label_a: "ผู้ชนะคู่ J-A",
    label_b: "ผู้ชนะคู่ J-B",
    score_a: null,
    score_b: null,
    best_of: 3,
    status: "wait",
    winner: null,
    scheduled_at: null,
    note: null,
    team_a: null,
    team_b: null,
  },
  {
    id: "J-J",
    code: "J-J",
    game_slug: "rov",
    division: "junior",
    round_name: "รอบ 8 ทีมสุดท้าย",
    round_order: 2,
    slot: 2,
    team_a_id: null,
    team_b_id: null,
    label_a: "ผู้ชนะคู่ J-C",
    label_b: "ผู้ชนะคู่ J-D",
    score_a: null,
    score_b: null,
    best_of: 3,
    status: "wait",
    winner: null,
    scheduled_at: null,
    note: null,
    team_a: null,
    team_b: null,
  },
  {
    id: "J-K",
    code: "J-K",
    game_slug: "rov",
    division: "junior",
    round_name: "รอบ 8 ทีมสุดท้าย",
    round_order: 2,
    slot: 3,
    team_a_id: null,
    team_b_id: null,
    label_a: "ผู้ชนะคู่ J-E",
    label_b: "ผู้ชนะคู่ J-F",
    score_a: null,
    score_b: null,
    best_of: 3,
    status: "wait",
    winner: null,
    scheduled_at: null,
    note: null,
    team_a: null,
    team_b: null,
  },
  {
    id: "J-L",
    code: "J-L",
    game_slug: "rov",
    division: "junior",
    round_name: "รอบ 8 ทีมสุดท้าย",
    round_order: 2,
    slot: 4,
    team_a_id: null,
    team_b_id: null,
    label_a: "ผู้ชนะคู่ J-G",
    label_b: "ผู้ชนะคู่ J-H",
    score_a: null,
    score_b: null,
    best_of: 3,
    status: "wait",
    winner: null,
    scheduled_at: null,
    note: null,
    team_a: null,
    team_b: null,
  },
  {
    id: "J-M",
    code: "J-M",
    game_slug: "rov",
    division: "junior",
    round_name: "รอบรองชนะเลิศ",
    round_order: 3,
    slot: 1,
    team_a_id: null,
    team_b_id: null,
    label_a: "ผู้ชนะคู่ J-I",
    label_b: "ผู้ชนะคู่ J-J",
    score_a: null,
    score_b: null,
    best_of: 3,
    status: "wait",
    winner: null,
    scheduled_at: null,
    note: null,
    team_a: null,
    team_b: null,
  },
  {
    id: "J-N",
    code: "J-N",
    game_slug: "rov",
    division: "junior",
    round_name: "รอบรองชนะเลิศ",
    round_order: 3,
    slot: 2,
    team_a_id: null,
    team_b_id: null,
    label_a: "ผู้ชนะคู่ J-K",
    label_b: "ผู้ชนะคู่ J-L",
    score_a: null,
    score_b: null,
    best_of: 3,
    status: "wait",
    winner: null,
    scheduled_at: null,
    note: null,
    team_a: null,
    team_b: null,
  },
  {
    id: "J-O",
    code: "J-O",
    game_slug: "rov",
    division: "junior",
    round_name: "รอบชิงชนะเลิศ",
    round_order: 4,
    slot: 1,
    team_a_id: null,
    team_b_id: null,
    label_a: "ผู้ชนะคู่ J-M",
    label_b: "ผู้ชนะคู่ J-N",
    score_a: null,
    score_b: null,
    best_of: 3,
    status: "wait",
    winner: null,
    scheduled_at: null,
    note: null,
    team_a: null,
    team_b: null,
  },
  {
    id: "S-A",
    code: "S-A",
    game_slug: "rov",
    division: "senior",
    round_name: "รอบคัดเลือก",
    round_order: 1,
    slot: 1,
    team_a_id: "t24",
    team_b_id: "t25",
    label_a: null,
    label_b: null,
    score_a: null,
    score_b: null,
    best_of: 3,
    status: "wait",
    winner: null,
    scheduled_at: null,
    note: null,
    team_a: teamById["t24"],
    team_b: teamById["t25"],
  },
  {
    id: "S-B",
    code: "S-B",
    game_slug: "rov",
    division: "senior",
    round_name: "รอบคัดเลือก",
    round_order: 1,
    slot: 2,
    team_a_id: "t20",
    team_b_id: "t29",
    label_a: null,
    label_b: null,
    score_a: null,
    score_b: null,
    best_of: 3,
    status: "wait",
    winner: null,
    scheduled_at: null,
    note: null,
    team_a: teamById["t20"],
    team_b: teamById["t29"],
  },
  {
    id: "S-C",
    code: "S-C",
    game_slug: "rov",
    division: "senior",
    round_name: "รอบคัดเลือก",
    round_order: 1,
    slot: 3,
    team_a_id: "t21",
    team_b_id: "t28",
    label_a: null,
    label_b: null,
    score_a: null,
    score_b: null,
    best_of: 3,
    status: "wait",
    winner: null,
    scheduled_at: null,
    note: null,
    team_a: teamById["t21"],
    team_b: teamById["t28"],
  },
  {
    id: "S-D",
    code: "S-D",
    game_slug: "rov",
    division: "senior",
    round_name: "รอบคัดเลือก",
    round_order: 1,
    slot: 4,
    team_a_id: "t23",
    team_b_id: "t26",
    label_a: null,
    label_b: null,
    score_a: null,
    score_b: null,
    best_of: 3,
    status: "wait",
    winner: null,
    scheduled_at: null,
    note: null,
    team_a: teamById["t23"],
    team_b: teamById["t26"],
  },
  {
    id: "S-E",
    code: "S-E",
    game_slug: "rov",
    division: "senior",
    round_name: "รอบคัดเลือก",
    round_order: 1,
    slot: 5,
    team_a_id: "t22",
    team_b_id: "t27",
    label_a: null,
    label_b: null,
    score_a: null,
    score_b: null,
    best_of: 3,
    status: "wait",
    winner: null,
    scheduled_at: null,
    note: null,
    team_a: teamById["t22"],
    team_b: teamById["t27"],
  },
  {
    id: "S-F",
    code: "S-F",
    game_slug: "rov",
    division: "senior",
    round_name: "รอบ 8 ทีมสุดท้าย",
    round_order: 2,
    slot: 1,
    team_a_id: "t17",
    team_b_id: null,
    label_a: null,
    label_b: "ผู้ชนะคู่ S-A",
    score_a: null,
    score_b: null,
    best_of: 3,
    status: "wait",
    winner: null,
    scheduled_at: null,
    note: null,
    team_a: teamById["t17"],
    team_b: null,
  },
  {
    id: "S-G",
    code: "S-G",
    game_slug: "rov",
    division: "senior",
    round_name: "รอบ 8 ทีมสุดท้าย",
    round_order: 2,
    slot: 2,
    team_a_id: null,
    team_b_id: null,
    label_a: "ผู้ชนะคู่ S-B",
    label_b: "ผู้ชนะคู่ S-C",
    score_a: null,
    score_b: null,
    best_of: 3,
    status: "wait",
    winner: null,
    scheduled_at: null,
    note: null,
    team_a: null,
    team_b: null,
  },
  {
    id: "S-H",
    code: "S-H",
    game_slug: "rov",
    division: "senior",
    round_name: "รอบ 8 ทีมสุดท้าย",
    round_order: 2,
    slot: 3,
    team_a_id: "t18",
    team_b_id: null,
    label_a: null,
    label_b: "ผู้ชนะคู่ S-D",
    score_a: null,
    score_b: null,
    best_of: 3,
    status: "wait",
    winner: null,
    scheduled_at: null,
    note: null,
    team_a: teamById["t18"],
    team_b: null,
  },
  {
    id: "S-I",
    code: "S-I",
    game_slug: "rov",
    division: "senior",
    round_name: "รอบ 8 ทีมสุดท้าย",
    round_order: 2,
    slot: 4,
    team_a_id: "t19",
    team_b_id: null,
    label_a: null,
    label_b: "ผู้ชนะคู่ S-E",
    score_a: null,
    score_b: null,
    best_of: 3,
    status: "wait",
    winner: null,
    scheduled_at: null,
    note: null,
    team_a: teamById["t19"],
    team_b: null,
  },
  {
    id: "S-J",
    code: "S-J",
    game_slug: "rov",
    division: "senior",
    round_name: "รอบรองชนะเลิศ",
    round_order: 3,
    slot: 1,
    team_a_id: null,
    team_b_id: null,
    label_a: "ผู้ชนะคู่ S-F",
    label_b: "ผู้ชนะคู่ S-G",
    score_a: null,
    score_b: null,
    best_of: 3,
    status: "wait",
    winner: null,
    scheduled_at: null,
    note: null,
    team_a: null,
    team_b: null,
  },
  {
    id: "S-K",
    code: "S-K",
    game_slug: "rov",
    division: "senior",
    round_name: "รอบรองชนะเลิศ",
    round_order: 3,
    slot: 2,
    team_a_id: null,
    team_b_id: null,
    label_a: "ผู้ชนะคู่ S-H",
    label_b: "ผู้ชนะคู่ S-I",
    score_a: null,
    score_b: null,
    best_of: 3,
    status: "wait",
    winner: null,
    scheduled_at: null,
    note: null,
    team_a: null,
    team_b: null,
  },
  {
    id: "S-L",
    code: "S-L",
    game_slug: "rov",
    division: "senior",
    round_name: "รอบชิงชนะเลิศ",
    round_order: 4,
    slot: 1,
    team_a_id: null,
    team_b_id: null,
    label_a: "ผู้ชนะคู่ S-J",
    label_b: "ผู้ชนะคู่ S-K",
    score_a: null,
    score_b: null,
    best_of: 3,
    status: "wait",
    winner: null,
    scheduled_at: null,
    note: null,
    team_a: null,
    team_b: null,
  },
];

const DAY1 = "2026-09-09";
const DAY2 = "2026-09-10";
const DAY1_TITLE = "วันพุธที่ 9 กันยายน 2569 — รอบ 16 ทีม และรอบ 8 ทีม";
const DAY2_TITLE = "วันพฤหัสบดีที่ 10 กันยายน 2569 — รอบรองชนะเลิศถึงรอบชิงชนะเลิศ";

function slot(
  id: string,
  day: string,
  dayTitle: string,
  time: string,
  title: string,
  note: string,
  tag: ScheduleItem["tag"],
  sort: number,
): ScheduleItem {
  return { id, day, day_title: dayTitle, time, title, note: note || null, tag, sort };
}

export const fallbackSchedule: ScheduleItem[] = [
  slot("s1", DAY1, DAY1_TITLE, "08:30", "ลงทะเบียนนักกีฬาและตรวจรายชื่อ", "นำบัตรประจำตัวนักเรียนมาแสดง", "open", 1),
  slot("s2", DAY1, DAY1_TITLE, "09:00", "พิธีเปิดการแข่งขันและชี้แจงระเบียบ", "ครูที่ปรึกษาประจำทีมทุกทีมเข้าร่วม", null, 2),
  slot("s3", DAY1, DAY1_TITLE, "09:30", "ม.ต้น · รอบ 16 ทีม คู่ J-A ถึง J-D", "แพ้คัดออก Bo3", null, 3),
  slot("s4", DAY1, DAY1_TITLE, "10:30", "ม.ต้น · รอบ 16 ทีม คู่ J-E ถึง J-H", "แพ้คัดออก Bo3", null, 4),
  slot("s5", DAY1, DAY1_TITLE, "11:30", "ม.ปลาย · รอบคัดเลือก คู่ S-A ถึง S-C", "แพ้คัดออก Bo3", null, 5),
  slot("s6", DAY1, DAY1_TITLE, "12:00", "พักกลางวัน", "", null, 6),
  slot("s7", DAY1, DAY1_TITLE, "13:00", "ม.ปลาย · รอบคัดเลือก คู่ S-D ถึง S-E", "แพ้คัดออก Bo3", null, 7),
  slot("s8", DAY1, DAY1_TITLE, "14:00", "ม.ต้น · รอบ 8 ทีม", "แพ้คัดออก Bo3", null, 8),
  slot("s9", DAY1, DAY1_TITLE, "15:30", "ม.ปลาย · รอบ 8 ทีม", "แพ้คัดออก Bo3", null, 9),
  slot("s10", DAY1, DAY1_TITLE, "16:30", "ประกาศคู่รอบรองชนะเลิศทั้งสองรุ่น", "ประกาศหน้าห้องแข่งขันและบนเว็บไซต์", null, 10),
  slot("s11", DAY2, DAY2_TITLE, "09:00", "รายงานตัวนักกีฬา", "รายงานตัวก่อนเวลาแข่งขัน 15 นาที", "open", 1),
  slot("s12", DAY2, DAY2_TITLE, "09:30", "ม.ต้น · รอบรองชนะเลิศ", "แพ้คัดออก Bo3", null, 2),
  slot("s13", DAY2, DAY2_TITLE, "11:00", "ม.ปลาย · รอบรองชนะเลิศ", "แพ้คัดออก Bo3", null, 3),
  slot("s14", DAY2, DAY2_TITLE, "12:00", "พักกลางวัน", "", null, 4),
  slot("s15", DAY2, DAY2_TITLE, "13:30", "ม.ต้น · รอบชิงชนะเลิศ", "แพ้คัดออก Bo3", "key", 5),
  slot("s16", DAY2, DAY2_TITLE, "15:00", "ม.ปลาย · รอบชิงชนะเลิศ", "แพ้คัดออก Bo3", "key", 6),
  slot("s17", DAY2, DAY2_TITLE, "16:30", "พิธีมอบรางวัลและปิดการแข่งขัน", "มอบเงินรางวัลและเกียรติบัตร", null, 7),
];

/* กติกาตามระเบียบการแข่งขันกีฬาอีสปอร์ต (ROV TOURNAMENT 2026)
   ประกาศ ณ วันที่ 23 กรกฎาคม 2569 */
export const fallbackRules: Rule[] = [
  {
    id: "r1",
    heading: "ข้อ 2 · กติกาที่ใช้",
    body: "ใช้กติกาและข้อบังคับการแข่งขัน RoV Pro League ของบริษัท การีนา ออนไลน์ (ประเทศไทย) จำกัด ที่กำหนดใช้ในปัจจุบัน ทั้งนี้ต้องไม่ขัดหรือแย้งกับระเบียบฉบับนี้",
    sort: 1,
  },
  {
    id: "r2",
    heading: "ข้อ 3 · ประเภทการแข่งขัน",
    body: "แบ่งเป็น 2 รุ่น คือ รุ่นมัธยมศึกษาตอนต้น (ม.1–ม.3) และรุ่นมัธยมศึกษาตอนปลาย (ม.4–ม.6) รับสมัครรุ่นละไม่เกิน 16 ทีม",
    sort: 2,
  },
  {
    id: "r3",
    heading: "ข้อ 4 · คุณสมบัติของผู้เข้าแข่งขัน",
    body: "ต้องเป็นนักเรียนที่กำลังศึกษาอยู่ในโรงเรียนเบญจมราชูทิศ จังหวัดจันทบุรี ตามระดับชั้นที่ลงสมัคร · แต่ละทีมมีนักกีฬาตัวจริง 5 คน และตัวสำรอง 1 คน (มีหรือไม่มีก็ได้) รวมไม่เกิน 6 คน · ทุกทีมต้องมีครูที่ปรึกษาประจำทีม 1 คน ซึ่งเป็นครูหรือบุคลากรของโรงเรียน · นักกีฬา 1 คน ลงทะเบียนและแข่งขันได้เพียง 1 ทีมเท่านั้นตลอดรายการ",
    sort: 3,
  },
  {
    id: "r4",
    heading: "ข้อ 5 · วิธีจัดการแข่งขัน",
    body: "แข่งแบบแพ้คัดออก (Knockout) ทุกรอบ ตั้งแต่รอบแรกจนถึงรอบชิงชนะเลิศ ระบบ Best of 3 ทีมใดชนะ 2 ใน 3 เกมก่อนเป็นผู้ชนะและผ่านเข้ารอบต่อไป ทีมที่แพ้ตกรอบทันที",
    sort: 4,
  },
  {
    id: "r5",
    heading: "ข้อ 5.3 · การเลือกฮีโร่ (Global Ban-Pick)",
    body: "ฮีโร่ที่ทีมตนเองเลือกใช้ไปแล้วในเกมก่อนหน้า จะไม่สามารถนำกลับมาเลือกใช้ได้อีกในแมตช์นั้น ระบบจะรีเซ็ตใหม่เมื่อเริ่มแมตช์ใหม่",
    sort: 5,
  },
  {
    id: "r6",
    heading: "ข้อ 5.4 · การเลือกฝั่ง",
    body: "เกมที่ 1 สุ่มสิทธิ์การเลือกฝั่ง ส่วนเกมที่ 2 และเกมที่ 3 ให้ทีมที่แพ้ในเกมก่อนหน้าได้สิทธิ์เลือกฝั่ง",
    sort: 6,
  },
  {
    id: "r7",
    heading: "ข้อ 7 · การหยุดเกมและข้อปฏิบัติทางเทคนิค",
    body: "แต่ละทีมขอหยุดเกม (Pause) ได้ไม่เกิน 2 ครั้งต่อเกม ครั้งละไม่เกิน 3 นาที รวมไม่เกิน 6 นาทีต่อเกม เฉพาะกรณีปัญหาทางเทคนิค สัญญาณอินเทอร์เน็ต หรืออุปกรณ์ชำรุด · ห้ามกดหยุดเกมระหว่างเกิดการปะทะ (Team Fight) เว้นแต่ระบบเกมหยุดให้อัตโนมัติ · หากผู้เล่นหลุดระหว่างเลือกตัวละคร (Drafting) ให้แจ้งกรรมการทันทีเพื่อสร้างห้องใหม่ แล้ว Ban & Pick ตัวละครเดิมเหมือนก่อนหน้า 100%",
    sort: 7,
  },
  {
    id: "r8",
    heading: "ข้อ 8.2 · การรายงานตัว",
    body: "ให้มารายงานตัว ณ จุดที่คณะกรรมการกำหนด ก่อนเวลาการแข่งขัน 15 นาที หากเลยกำหนดเวลาแข่งขันไป 15 นาทีโดยไม่มีเหตุอันสมควร ให้ปรับทีมนั้นเป็นแพ้บาย",
    sort: 8,
  },
  {
    id: "r9",
    heading: "ข้อ 8.3 · วินัยและมารยาท",
    body: "ผู้เข้าแข่งขันต้องประพฤติตนให้สมกับความเป็นนักกีฬาที่ดี ห้ามใช้คำหยาบคาย พิมพ์ข้อความเยาะเย้ย หรือแสดงพฤติกรรมไม่เหมาะสม (Toxic / Trash Talk) ทั้งในเกมและนอกเกม หากฝ่าฝืนจะได้รับใบเตือน หากทำซ้ำจะถูกปรับแพ้ในเกมนั้นทันที",
    sort: 9,
  },
  {
    id: "r10",
    heading: "ข้อ 8.4–8.5 · การโกงและการสมยอมผล",
    body: "ห้ามใช้โปรแกรมโกง ดัดแปลงไฟล์เกม (Skin Hack) หรือใช้ข้อผิดพลาดของเกม (Bug) เพื่อสร้างความได้เปรียบ หากตรวจพบจะถูกตัดสิทธิ์ออกจากการแข่งขันทันที และรายงานพฤติกรรมต่อฝ่ายปกครองของโรงเรียน · ห้ามสมยอมผลการแข่งขัน (Match-Fixing) หากพบหลักฐานจะถูกปรับแพ้ทั้งสองทีม และตัดสิทธิ์การเข้าร่วมแข่งขันกีฬาอีสปอร์ตของโรงเรียนในอนาคต",
    sort: 10,
  },
  {
    id: "r11",
    heading: "ข้อ 10 · การประท้วงผลการแข่งขัน",
    body: "การประท้วงเป็นสิทธิ์ของครูที่ปรึกษาประจำทีมเท่านั้น โดยยื่นคำร้องเป็นลายลักษณ์อักษรพร้อมหลักฐานภาพถ่ายหรือวิดีโอต่อคณะกรรมการจัดการแข่งขัน ภายใน 15 นาทีหลังจบแมตช์นั้น",
    sort: 11,
  },
  {
    id: "r12",
    heading: "ข้อ 11–12 · การวินิจฉัยชี้ขาด",
    body: "กรณีมีปัญหาเกี่ยวกับการใช้ระเบียบนี้ หรือกรณีที่ไม่ได้ระบุไว้ ให้คณะกรรมการจัดการแข่งขันเป็นผู้วินิจฉัยชี้ขาดและถือเป็นที่สุด โดยคณะกรรมการจัดการแข่งขัน ROV TOURNAMENT 2026 เป็นผู้รักษาการตามระเบียบนี้",
    sort: 12,
  },
];

export const fallbackPrizes: Prize[] = [
  { id: "p1", place: "รางวัลชนะเลิศ", amount: "3,000 บาท", note: "พร้อมเกียรติบัตร", sort: 1 },
  { id: "p2", place: "รางวัลรองชนะเลิศอันดับ 1", amount: "2,000 บาท", note: "พร้อมเกียรติบัตร", sort: 2 },
  { id: "p3", place: "รางวัลรองชนะเลิศอันดับ 2", amount: "1,000 บาท", note: "พร้อมเกียรติบัตร", sort: 3 },
  {
    id: "p4",
    place: "ผู้เข้าร่วมการแข่งขันทุกคน",
    amount: "เกียรติบัตร",
    note: "เกียรติบัตรเข้าร่วมการแข่งขัน",
    sort: 4,
  },
];

export const fallbackFaqs: Faq[] = [
  {
    id: "f1",
    question: "แข่งกี่รุ่น แบ่งอย่างไร",
    answer: "แบ่งเป็นรุ่น ม.ต้น (ม.1–ม.3) และรุ่น ม.ปลาย (ม.4–ม.6) รับสมัครรุ่นละไม่เกิน 16 ทีม ปีนี้มีทีมเข้าแข่งขันรุ่น ม.ต้น 16 ทีม และรุ่น ม.ปลาย 13 ทีม",
    sort: 1,
  },
  {
    id: "f2",
    question: "แข่งระบบอะไร รอบชิงชนะเลิศ Bo เท่าไร",
    answer: "แพ้คัดออก (Knockout) ทุกรอบ ตั้งแต่รอบแรกจนถึงรอบชิงชนะเลิศ ทุกแมตช์เป็น Bo3 ชนะ 2 ใน 3 เกมก่อนผ่านเข้ารอบ ทีมที่แพ้ตกรอบทันที",
    sort: 2,
  },
  {
    id: "f3",
    question: "ต้องมารายงานตัวก่อนกี่นาที",
    answer: "ก่อนเวลาแข่งขัน 15 นาที ณ จุดรายงานตัวที่คณะกรรมการกำหนด หากเลยเวลาแข่งขันไป 15 นาทีโดยไม่มีเหตุอันสมควร จะถูกปรับเป็นแพ้บาย",
    sort: 3,
  },
  {
    id: "f4",
    question: "มีเงินรางวัลเท่าไร",
    answer: "แต่ละรุ่นมีรางวัลชนะเลิศ 3,000 บาท รองชนะเลิศอันดับ 1 จำนวน 2,000 บาท และรองชนะเลิศอันดับ 2 จำนวน 1,000 บาท พร้อมเกียรติบัตร ส่วนผู้เข้าร่วมทุกคนได้รับเกียรติบัตรเข้าร่วมการแข่งขัน",
    sort: 4,
  },
  {
    id: "f5",
    question: "ใครมีสิทธิ์ยื่นประท้วงผลการแข่งขัน",
    answer: "ครูที่ปรึกษาประจำทีมเท่านั้น โดยยื่นเป็นลายลักษณ์อักษรพร้อมหลักฐานภาพถ่ายหรือวิดีโอ ภายใน 15 นาทีหลังจบแมตช์",
    sort: 5,
  },
  {
    id: "f6",
    question: "ขอหยุดเกมได้กี่ครั้ง",
    answer: "ทีมละไม่เกิน 2 ครั้งต่อเกม ครั้งละไม่เกิน 3 นาที รวมไม่เกิน 6 นาทีต่อเกม เฉพาะกรณีปัญหาทางเทคนิค สัญญาณอินเทอร์เน็ต หรืออุปกรณ์ชำรุดเท่านั้น",
    sort: 6,
  },
  {
    id: "f7",
    question: "ติดตามผลการแข่งขันได้อย่างไร",
    answer: "ผลอัปเดตสดบนหน้าผลสดของเว็บไซต์ทันทีที่กรรมการบันทึกคะแนนที่โต๊ะกรรมการ",
    sort: 7,
  },
];

export const fallbackNews: NewsPost[] = [
  {
    id: "n1",
    slug: "prakat-phang-sai",
    title: "ประกาศผังสายการแข่งขันทั้งสองรุ่น",
    excerpt: "รุ่น ม.ต้น 16 ทีม และรุ่น ม.ปลาย 13 ทีม ตรวจสอบคู่แข่งขันได้แล้วบนเว็บไซต์",
    body: "คณะกรรมการจัดการแข่งขันได้ประกาศผังสายการแข่งขันอย่างเป็นทางการทั้งสองรุ่นแล้ว\n\nรุ่น ม.ต้น มี 16 ทีม เริ่มจากรอบ 16 ทีม ส่วนรุ่น ม.ปลาย มี 13 ทีม โดยทีมวางอันดับ 1 ถึง 3 ผ่านเข้ารอบ 8 ทีมโดยอัตโนมัติ\n\nทุกรอบแข่งแบบแพ้คัดออก Bo3 ตั้งแต่รอบแรกจนถึงรอบชิงชนะเลิศ ทีมที่แพ้ตกรอบทันที\n\nขอให้ทุกทีมมารายงานตัวก่อนเวลาแข่งขันอย่างน้อย 15 นาที",
    cover_url: null,
    published: true,
    pinned: true,
    published_at: "2026-09-05T10:00:00+07:00",
  },
  {
    id: "n2",
    slug: "rabiap-kan-khaengkhan",
    title: "ประกาศระเบียบการแข่งขัน ROV TOURNAMENT 2026",
    excerpt: "ระเบียบ 12 ข้อ ครอบคลุมคุณสมบัติผู้เข้าแข่งขัน วิธีจัดการแข่งขัน การหยุดเกม วินัย บทลงโทษ และรางวัล",
    body: "คณะกรรมการจัดการแข่งขันได้ประกาศระเบียบการแข่งขันกีฬาอีสปอร์ต (ROV TOURNAMENT 2026) ณ วันที่ 23 กรกฎาคม 2569\n\nระเบียบครอบคลุมกติกาที่ใช้ ประเภทการแข่งขัน คุณสมบัติผู้เข้าแข่งขัน วิธีจัดการแข่งขัน การหยุดเกมและข้อปฏิบัติทางเทคนิค วินัยและบทลงโทษ รางวัล และการประท้วงผลการแข่งขัน\n\nครูที่ปรึกษาประจำทีมทุกทีมมีหน้าที่ชี้แจงระเบียบให้นักกีฬาในสังกัดรับทราบก่อนวันแข่งขัน อ่านฉบับเต็มได้ที่หน้ากติกาของเว็บไซต์",
    cover_url: null,
    published: true,
    pinned: false,
    published_at: "2026-07-23T09:00:00+07:00",
  },
  {
    id: "n3",
    slug: "prakat-thim-mi-sit",
    title: "ประกาศรายชื่อทีมที่มีสิทธิ์แข่งขัน รวม 29 ทีม",
    excerpt: "ทีมที่ผ่านการตรวจสอบคุณสมบัติและมีสิทธิ์ลงแข่งขัน แบ่งเป็นรุ่น ม.ต้น 16 ทีม และรุ่น ม.ปลาย 13 ทีม",
    body: "การรับสมัครปิดรับเมื่อวันที่ 20 สิงหาคม 2569 ฝ่ายจัดการแข่งขันได้ตรวจสอบคุณสมบัติและประกาศรายชื่อทีมที่มีสิทธิ์ลงแข่งขันรวม 29 ทีม แบ่งเป็นรุ่น ม.ต้น 16 ทีม และรุ่น ม.ปลาย 13 ทีม\n\nทีมที่ไม่ปรากฏในผังสายการแข่งขันถือว่าไม่ได้รับสิทธิ์ลงแข่งขันในครั้งนี้\n\nฝ่ายจัดการแข่งขันขอขอบคุณนักเรียนและครูที่ปรึกษาประจำทีมทุกท่าน",
    cover_url: null,
    published: true,
    pinned: false,
    published_at: "2026-08-21T18:00:00+07:00",
  },
];

export const fallbackGallery: GalleryItem[] = [];

export const fallbackSponsors: Sponsor[] = [
  { id: "sp1", name: "สมาคมกีฬาแห่งจังหวัดจันทบุรี", tier: "host", logo_url: null, url: null, sort: 1 },
  { id: "sp2", name: "โรงเรียนเบญจมราชูทิศ จังหวัดจันทบุรี", tier: "host", logo_url: null, url: null, sort: 2 },
  {
    id: "sp3",
    name: "คณะกรรมการจัดการแข่งขัน ROV TOURNAMENT 2026",
    tier: "main",
    logo_url: null,
    url: null,
    sort: 3,
  },
];
